# http 容器
server:
  port: 80

# 同一个jvm中如果跑多个任务 请修改appName 为不同的内容
appName: "spring.boot.web.model"

# spring boot config
spring:
  application:
    name: ${appName}
  profiles:
    active: dev
  jmx:
    default-domain: ${appName}




# mybatis
mybatis:
  # mapper 扫描
  mapper-locations: classpath*:com/haotian/**/*Mapper.xml
  # 别名扫描的包
  type-aliases-package: com.haotian.development.entity
  configuration:
    # 下划线，驼峰转换
    map-underscore-to-camel-case: true
    # 开发过程中使用重写日志实现 为了打印 mybatis 日志到 控制台
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis 分页插件配置
pagehelper:
  # 方言
  helperDialect: mysql
  # 分页合理化
  reasonable: false
  # 传入pageSize 为0 则查询所有
  page-size-zero: true