# http 容器
server:
  port: 8080

# spring boot config
spring:
  application:
    name: "spring.boot.web.model"
  profiles:
    active: dev
  jmx:
    default-domain: "SpringBootWebModel"
    server:

# mybatis
mybatis:
  mapper-locations: classpath*:com/haotian/**/mapper/xml/*.xml
  configuration:
    # 自动驼峰转换
    map-underscore-to-camel-case: true


